"""Initial database schema

Revision ID: 712b48efc859
Revises: 
Create Date: 2024-05-24 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '712b48efc859'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # --- Step 1: Create all tables first ---
    op.create_table('users',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('username', sa.String(length=50), nullable=False),
        sa.Column('email', sa.String(length=100), nullable=False),
        sa.Column('hashed_password', sa.String(length=255), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('is_superuser', sa.Boolean(), nullable=True),
        sa.Column('score', sa.Integer(), nullable=False),
        sa.Column('earned_badges', sa.ARRAY(sa.String(length=50)), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)

    op.create_table('media_items',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('file_url', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('latitude', sa.Float(), nullable=True),
        sa.Column('longitude', sa.Float(), nullable=True),
        sa.Column('sighting_timestamp', sa.DateTime(timezone=True), nullable=True),
        sa.Column('original_filename', sa.String(length=255), nullable=True),
        sa.Column('content_type', sa.String(length=100), nullable=True),
        sa.Column('file_size_bytes', sa.Integer(), nullable=True),
        sa.Column('species_ai_prediction', sa.String(), nullable=True),
        sa.Column('health_status_ai_prediction', sa.String(), nullable=True),
        sa.Column('ai_confidence_score', sa.Float(), nullable=True),
        sa.Column('ai_model_version', sa.String(), nullable=True),
        sa.Column('ai_processing_status', sa.String(), nullable=False),
        sa.Column('validated_species', sa.String(), nullable=True),
        sa.Column('validated_health_status', sa.String(), nullable=True),
        sa.Column('validation_score', sa.Integer(), nullable=False),
        sa.Column('is_validated_by_community', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_items_id'), 'media_items', ['id'], unique=False)

    op.create_table('validation_votes',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('media_item_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('vote_on_species', sa.Boolean(), nullable=True),
        sa.Column('corrected_species_name', sa.String(length=255), nullable=True),
        sa.Column('vote_on_health', sa.Boolean(), nullable=True),
        sa.Column('corrected_health_status', sa.String(length=100), nullable=True),
        sa.Column('comment', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        # --- FIX IS HERE: We move the foreign key definitions to the end ---
        # sa.ForeignKeyConstraint(['media_item_id'], ['media_items.id'], ), <-- We move this
        # sa.ForeignKeyConstraint(['user_id'], ['users.id'], ), <-- We move this
        sa.PrimaryKeyConstraint('id'),
        # sa.UniqueConstraint('user_id', 'media_item_id', name='uq_user_media_vote') <-- We move this
    )
    op.create_index(op.f('ix_validation_votes_id'), 'validation_votes', ['id'], unique=False)
    op.create_index(op.f('ix_validation_votes_media_item_id'), 'validation_votes', ['media_item_id'], unique=False)
    op.create_index(op.f('ix_validation_votes_user_id'), 'validation_votes', ['user_id'], unique=False)
    
    # --- Step 2: Create all foreign keys and constraints AFTER all tables exist ---
    op.create_foreign_key('fk_validation_votes_user_id', 'validation_votes', 'users', ['user_id'], ['id'])
    op.create_foreign_key('fk_validation_votes_media_item_id', 'validation_votes', 'media_items', ['media_item_id'], ['id'])
    op.create_unique_constraint('uq_user_media_vote', 'validation_votes', ['user_id', 'media_item_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_media_vote', 'validation_votes', type_='unique')
    op.drop_constraint('fk_validation_votes_media_item_id', 'validation_votes', type_='foreignkey')
    op.drop_constraint('fk_validation_votes_user_id', 'validation_votes', type_='foreignkey')
    
    op.drop_index(op.f('ix_validation_votes_user_id'), table_name='validation_votes')
    op.drop_index(op.f('ix_validation_votes_media_item_id'), table_name='validation_votes')
    op.drop_index(op.f('ix_validation_votes_id'), table_name='validation_votes')
    op.drop_table('validation_votes')
    
    op.drop_index(op.f('ix_media_items_id'), table_name='media_items')
    op.drop_table('media_items')
    
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###